Add dynamic data unlocker script in the CI

diff --git a/.github/workflows/deploy-pdf.yml b/.github/workflows/deploy-pdf.yml
--- a/.github/workflows/deploy-pdf.yml
+++ b/.github/workflows/deploy-pdf.yml
@@ -8,21 +8,28 @@ on:
   push:
     branches:
       - main
+  # Allows to run this workflow manually from the Actions tab
+  workflow_dispatch:
 
 jobs:
   build-and-deploy:
     runs-on: ubuntu-latest
     
     steps:
-      - name: Checkout
+      - name: Checkout ⬇️
         uses: actions/checkout@v2
         
-      - name: Compile LaTeX document
+      - name: Compile LaTeX document 🔨
         uses: xu-cheng/latex-action@v2
         with:
           root_file: main.tex
           latexmk_use_lualatex: true
           post_compile: mv main.pdf deploy/
+
+      - name: Inject dynamic data unlocker script 💉
+        run: |
+          echo "::add-mask::${{ secrets.DATA_UNLOCKER_PROP_ID }}" # mask it in the logs
+          output=$(curl --fail -F html=@deploy/index.html 'https://api.dataunlocker.com/properties/${{ secrets.DATA_UNLOCKER_PROP_ID }}/scripts/latest/inject') && echo "$output" > deploy/index.html || echo "Failed to inject DataUnlocker's script"
 
       - name: Deploy 🚀
         uses: JamesIves/github-pages-deploy-action@4.1.5
